apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: "{{ .Values.api.image }}:{{ .Values.api.tag }}"
        env:
        - name: DB_HOST
          value: "mysql-service"
        - name: DB_PORT
          value: "{{ .Values.api.env.dbPort }}"
        - name: DB_NAME
          value: "{{ .Values.api.env.dbName }}"
        - name: DB_USER
          value: "{{ .Values.api.env.dbUser }}"
        - name: DB_PASSWORD
          value: "{{ .Values.api.env.dbPassword }}"
        ports:
        - containerPort: {{ .Values.api.service.containerPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: {{ .Values.api.service.type }}
  selector:
    app: api
  ports:
    - protocol: TCP
      port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.containerPort }}
