apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: "{{ .Values.mysql.image }}:{{ .Values.mysql.tag }}"
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "{{ .Values.mysql.env.rootPassword }}"
        - name: MYSQL_DATABASE
          value: "{{ .Values.mysql.env.database }}"
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: {{ .Values.mysql.service.port }}
      targetPort: 3306
